name: Docker Compose Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create external Docker networks
        run: |
          docker network create service_employee_network || true
          
      - name: Find .env file before creating .env
        run: |
          echo "Szukam pliku .env..."
          find . -name ".env" -print

      - name: Write .env file from GitHub Secret
        run: |
          echo "Current working directory:" 
          pwd
          printf "%s" "${{ secrets.EMPLOYEE_ENV_FILE }}" > employee_manager/.env
      - name: Debug .env
        run: |
          echo "--- employee_manager/.env ---"
          cat employee_manager/.env
      - name: Find .env file after creating
        run: |
          echo "Szukam pliku .env..."
          find . -name ".env" -print
    
      - name: Build and start containers
        working-directory: docker
        run: |  
          echo "Current working directory:"
          pwd
          docker-compose up -d --build

          

      - name: Wait for services to start
        run: |
          echo "Waiting for services to become healthy..."
          sleep 20
          docker logs docker_employee-db_1
          
          docker ps -a

      - name: Check if API Gateway is running
        run: |
          curl --fail http://localhost:8003/employee/schedules || (echo "Employee manager not responding" && exit 1)

      - name: Tear down containers and networks
        if: always()
        working-directory: docker
        run: |
          docker-compose down -v
          docker network rm service_employee_network || true
